Repository 2024-TikiTaka/be-triptroop, pull requests merged in 2024-06, with the labels that each got.

#75 #61 나의 신고 목록 (닉네임) 조회
  src/main/java/com/tikitaka/triptroop/report/controller/ReportController.java
  src/main/java/com/tikitaka/triptroop/report/domain/entity/Report.java
  src/main/java/com/tikitaka/triptroop/report/domain/repository/ReportRepository.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
  src/main/java/com/tikitaka/triptroop/user/domain/repository/ProfileRepository.java
Labels: 🔧Refactor

#80 #79 엔티티 연관관계 삭제
  src/main/java/com/tikitaka/triptroop/block/domain/entity/Block.java
  src/main/java/com/tikitaka/triptroop/block/dto/response/BlockTableResponse.java
  src/main/java/com/tikitaka/triptroop/report/domain/entity/Report.java
Labels: 🔧Refactor

#84 #83 이미지 업로드 로직 리팩터링
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/image/util/FileUploadUtils.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleParticipantsResponse.java
  src/main/java/com/tikitaka/triptroop/user/dto/response/UserProfileResponse.java
  src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
Labels: 🔧Refactor

#89 #86 개인 채팅방 생성
  src/main/java/com/tikitaka/triptroop/TriptroopApplication.java
  src/main/java/com/tikitaka/triptroop/chat/controller/ChatRoomController.java
  src/main/java/com/tikitaka/triptroop/chat/controller/MessageController.java
  src/main/java/com/tikitaka/triptroop/chat/controller/WebSocketController.java
  src/main/java/com/tikitaka/triptroop/chat/controller/WebSocketEventListener.java
  src/main/java/com/tikitaka/triptroop/chat/domain/entity/ChatRoom.java
  src/main/java/com/tikitaka/triptroop/chat/domain/entity/Message.java
  src/main/java/com/tikitaka/triptroop/chat/domain/repository/ChatRepository.java
  src/main/java/com/tikitaka/triptroop/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/tikitaka/triptroop/chat/domain/repository/MessageRepository.java
  src/main/java/com/tikitaka/triptroop/chat/domain/type/ChatRoomType.java
  src/main/java/com/tikitaka/triptroop/chat/dto/request/ChatRequest.java
  src/main/java/com/tikitaka/triptroop/chat/dto/request/PrivateChatRoomCreateRequest.java
  src/main/java/com/tikitaka/triptroop/chat/dto/request/WebSocketChatRequest.java
  src/main/java/com/tikitaka/triptroop/chat/dto/response/ChatResponse.java
  src/main/java/com/tikitaka/triptroop/chat/service/ChatRoomService.java
  src/main/java/com/tikitaka/triptroop/chat/service/ChatService.java
  src/main/java/com/tikitaka/triptroop/chat/service/MessageService.java
Labels: ✨ Feature

#90 #88 일정,계획 수정 기능
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleItemUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ✨ Feature

#91 #85 여행지 소개 댓글 등록 및 조회
  src/main/java/com/tikitaka/triptroop/travel/controller/TravelCommentController.java
  src/main/java/com/tikitaka/triptroop/travel/domain/entity/TravelComment.java
  src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelCommentRepository.java
  src/main/java/com/tikitaka/triptroop/travel/dto/TravelCommentsDto.java
  src/main/java/com/tikitaka/triptroop/travel/dto/TravelDto.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelCommentResponse.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelCommentsResponse.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelDetailResponse.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java
  src/main/java/com/tikitaka/triptroop/travel/service/TravelCommentService.java
  src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
Labels: ✨ Feature

#103 #102 일정 계획 삭제 기능 완료
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ✨ Feature

#105 #82 회원 프로필 기능 구현
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
  src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java
  src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java
  src/main/java/com/tikitaka/triptroop/user/controller/UserController.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/Profile.java
  src/main/java/com/tikitaka/triptroop/user/domain/repository/ProfileRepository.java
  src/main/java/com/tikitaka/triptroop/user/domain/repository/UserRepository.java
  src/main/java/com/tikitaka/triptroop/user/dto/response/ProfileResponse.java
  src/main/java/com/tikitaka/triptroop/user/dto/response/UserProfileResponse.java
  src/main/java/com/tikitaka/triptroop/user/service/AuthService.java
  src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
  src/main/java/com/tikitaka/triptroop/user/service/UserService.java
Labels: ✨ Feature, 🔧Refactor

#106 #104 일정 신청 승인 반려 기능
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleParticipant.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantAcceptRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantRejectedRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleParticipantRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
Labels: ✨ Feature

#108 README.md 수정
  README.md
Labels: 📚 Docs

#109 #107 일정 상세 조회문 코드 수정
  src/main/java/com/tikitaka/triptroop/common/exception/ForbiddenException.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryCustom.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleDetailResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleInformationResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleItemInfoResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleParticipantProfileResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: 🔧Refactor

#112 #110 일정 공개여부 변경 구현
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ✨ Feature

#114 #94 나의 신고 등록
  src/main/java/com/tikitaka/triptroop/common/dto/response/ApiResponse.java
  src/main/java/com/tikitaka/triptroop/report/controller/ReportController.java
  src/main/java/com/tikitaka/triptroop/report/domain/entity/Report.java
  src/main/java/com/tikitaka/triptroop/report/dto/request/ReportRequest.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
Labels: ✨ Feature

#117 #113 일정 신청 유효성 검사 로직 추가
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleParticipantRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ✨ Feature

#119 #116 나의 신고 등록 (수정) 완료
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/report/controller/ReportController.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
Labels: 🔧Refactor

#135 #134 리턴 값 변경
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
Labels: 🔧Refactor

#144 #118 일정 리뷰 CRUD
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleParticipant.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleParticipantRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleReviewRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
Labels: ✨ Feature

#146 #145 Security 설정 변경 및 회원 탈퇴 로직 수정
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java
  src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java
  src/main/java/com/tikitaka/triptroop/user/controller/UserController.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
  src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
Labels: 🔧Refactor

#150 #149 로그아웃 경로 security 허용 경로 추가
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
Labels: 🐞Bug

#159 #158 Acess Token 재발급
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/exception/AuthException.java
  src/main/java/com/tikitaka/triptroop/common/exception/handler/GeneralExceptionHandler.java
  src/main/java/com/tikitaka/triptroop/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/tikitaka/triptroop/common/security/util/TokenUtils.java
  src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
  src/main/java/com/tikitaka/triptroop/user/service/AuthService.java
Labels: ✨ Feature

#161 #160 회원 가입 검증 메시지 추가 및 @Valid 응답 형식 변경
  src/main/java/com/tikitaka/triptroop/common/dto/response/ApiResponse.java
  src/main/java/com/tikitaka/triptroop/common/exception/handler/GeneralExceptionHandler.java
  src/main/java/com/tikitaka/triptroop/user/dto/request/SignUpRequest.java
  src/main/java/com/tikitaka/triptroop/user/service/UserService.java
Labels: 🔧Refactor

#162 #121 관리자 > 회원관리 > 회원 상세 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminUserController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/AdminUserRepository.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminUserRepository.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminUserDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminUserService.java
  src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java
  src/main/java/com/tikitaka/triptroop/inquirie/domain/entity/Inquirie.java
  src/main/java/com/tikitaka/triptroop/inquirie/domain/type/InquirieKind.java
  src/main/java/com/tikitaka/triptroop/interest/domain/repository/InterestRepository.java
  src/main/java/com/tikitaka/triptroop/interest/dto/response/InterestResponse.java
  src/main/java/com/tikitaka/triptroop/interest/dto/response/UserInterestResponse.java
Labels: ✨ Feature

#164 친구목록 조회 수정
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/friend/controller/FriendController.java
  src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java
  src/main/java/com/tikitaka/triptroop/friend/domain/repository/FriendRepository.java
  src/main/java/com/tikitaka/triptroop/friend/dto/response/FriendResponse.java
  src/main/java/com/tikitaka/triptroop/friend/service/FriendService.java
Labels: 🐞Bug

#166 #122 관리자 > 회원 관리 > 회원 등록
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminUserController.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminUserSaveRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminUserSaveResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminUserService.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
Labels: ✨ Feature

#167 #124 관리자 > 회원 삭제
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminUserController.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminUserService.java
Labels: ✨ Feature

#168 친구 신청
  src/main/java/com/tikitaka/triptroop/friend/controller/FriendController.java
  src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java
  src/main/java/com/tikitaka/triptroop/friend/dto/request/FriendAddRequest.java
  src/main/java/com/tikitaka/triptroop/friend/dto/request/FriendRequest.java
  src/main/java/com/tikitaka/triptroop/friend/dto/response/FriendAcceptorInfoResponse.java
  src/main/java/com/tikitaka/triptroop/friend/service/FriendService.java
Labels: ✨ Feature

#169 친구 신청 수락
  src/main/java/com/tikitaka/triptroop/friend/controller/FriendController.java
  src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java
  src/main/java/com/tikitaka/triptroop/friend/domain/repository/FriendRepository.java
  src/main/java/com/tikitaka/triptroop/friend/service/FriendService.java
Labels: ✨ Feature

#170 친구 삭제
  src/main/java/com/tikitaka/triptroop/friend/controller/FriendController.java
  src/main/java/com/tikitaka/triptroop/friend/domain/entity/Friend.java
  src/main/java/com/tikitaka/triptroop/friend/service/FriendService.java
Labels: ✨ Feature

#173 알림 패키지 작성
  src/main/java/com/tikitaka/triptroop/notification/controller/NotificationController.java
  src/main/java/com/tikitaka/triptroop/notification/domain/entity/Notification.java
  src/main/java/com/tikitaka/triptroop/notification/domain/repository/NotificationRepository.java
  src/main/java/com/tikitaka/triptroop/notification/domain/type/NotificationType.java
  src/main/java/com/tikitaka/triptroop/notification/dto/request/NotificationRequest.java
  src/main/java/com/tikitaka/triptroop/notification/dto/response/NotificationResponse.java
  src/main/java/com/tikitaka/triptroop/notification/service/NotificationService.java
Labels: ⚙️Setting

#176 #125 관리자 > 문의 관리 > 문의 목록 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminUserController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminInquiryRepository.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminUserRepository.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminUserSaveRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminUserUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminUserService.java
  src/main/java/com/tikitaka/triptroop/inquirie/domain/type/InquirieKind.java
  src/main/java/com/tikitaka/triptroop/inquiry/domain/entity/Inquiry.java
  src/main/java/com/tikitaka/triptroop/inquiry/domain/type/InquiryKind.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/response/InquiryListResponse.java
  src/main/java/com/tikitaka/triptroop/inquiry/service/InquiryService.java
  src/main/java/com/tikitaka/triptroop/interest/domain/entity/Interest.java
  src/main/java/com/tikitaka/triptroop/interest/domain/entity/UserInterest.java
  src/main/java/com/tikitaka/triptroop/interest/domain/repository/InterestRepository.java
  src/main/java/com/tikitaka/triptroop/interest/domain/repository/UserInterestRepository.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/Profile.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
Labels: ✨ Feature

#177 #126 관리자 > 문의 관리 > 문의 상세 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminInquiryRepository.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/image/domain/entity/Image.java
  src/main/java/com/tikitaka/triptroop/image/dto/response/ImageOriginalResponse.java
  src/main/java/com/tikitaka/triptroop/image/util/ImageUtils.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/response/InquiryDetailResponse.java
  src/main/java/com/tikitaka/triptroop/inquiry/service/InquiryService.java
  src/main/java/com/tikitaka/triptroop/report/dto/response/ReportDetailResponse.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
Labels: ✨ Feature

#178 #127 관리자 > 문의 관리 > 답변 등록
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/inquiry/domain/entity/Inquiry.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/request/InquiryReplyRequest.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/response/InquiryDetailResponse.java
  src/main/java/com/tikitaka/triptroop/inquiry/service/InquiryService.java
Labels: ✨ Feature

#195 #194 프론트엔드 관련 변경 및 리팩터링
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/email/controller/EmailController.java
  src/main/java/com/tikitaka/triptroop/user/controller/AuthController.java
  src/main/java/com/tikitaka/triptroop/user/controller/ProfileController.java
  src/main/java/com/tikitaka/triptroop/user/controller/UserController.java
  src/main/java/com/tikitaka/triptroop/user/domain/repository/ProfileRepository.java
  src/main/java/com/tikitaka/triptroop/user/dto/response/CurrentUserResponse.java
  src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
  src/main/java/com/tikitaka/triptroop/user/service/UserService.java
Labels: 🔧Refactor

#199 #196 일정 코드 리펙토링
  src/main/java/com/tikitaka/triptroop/place/domain/entity/Place.java
  src/main/java/com/tikitaka/triptroop/place/domain/repository/PlaceRepository.java
  src/main/java/com/tikitaka/triptroop/place/dto/response/PlaceResponse.java
  src/main/java/com/tikitaka/triptroop/place/service/PlaceService.java
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleParticipant.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleParticipantRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryCustom.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleItemUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleDetailResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleItemInfoResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleParticipantService.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: 🔧Refactor

#201 #127 관리자 > 문의 관리 > 답변 등록 (수정)
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminUserController.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminCategorySaveRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminUserSaveRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminCategoryResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminUserDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminUserResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminUserSaveResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminUserService.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/response/InquiryDetailResponse.java
  src/main/java/com/tikitaka/triptroop/inquiry/dto/response/InquiryListResponse.java
Labels: 🔧Refactor

#202 #129 관리자 > 카테고리 관리 > 카테고리 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminCategoryController.java
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminCategoryRepository.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminInquiryRepository.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminCategoryResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminInquiryDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminInquiryListResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminCategoryService.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminInquiryService.java
  src/main/java/com/tikitaka/triptroop/image/dto/request/AdminInquiryReplyRequest.java
Labels: ✨ Feature

#204 #131 관리자 > 카테고리 관리 > 카테고리 수정
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminCategoryController.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminCategoryService.java
  src/main/java/com/tikitaka/triptroop/category/domain/entity/Category.java
Labels: ✨ Feature

#205 /#136 관리자 > 공지 관리 > 공지 목록 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminNoticeController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminNoticeRepository.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java
  src/main/java/com/tikitaka/triptroop/notice/domain/entity/Notice.java
  src/main/java/com/tikitaka/triptroop/notice/domain/type/NoticeKind.java
  src/main/java/com/tikitaka/triptroop/notice/domain/type/NoticeStatus.java
Labels: ✨ Feature

#206 #137 관리자 > 공지 관리 > 공지 상세 조회
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminCategoryController.java
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminNoticeController.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminInquiryReplyRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminCategoryResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminNoticeResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminCategoryService.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminInquiryService.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java
  src/main/java/com/tikitaka/triptroop/block/dto/response/BlockTableResponse.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/image/domain/entity/Image.java
  src/main/java/com/tikitaka/triptroop/image/domain/repository/ImageRepository.java
  src/main/java/com/tikitaka/triptroop/image/domain/type/ImageKind.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/notice/domain/entity/Notice.java
  src/main/java/com/tikitaka/triptroop/report/dto/response/ReportDetailResponse.java
  src/main/java/com/tikitaka/triptroop/report/dto/response/ReportTableResponse.java
Labels: ✨ Feature

#207 #138 관리자 > 공지 관리 > 공지 등록
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminInquiryController.java
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminNoticeController.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminInquiryReplyRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminNoticeRequest.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminUserSaveRequest.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminInquiryService.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/notice/domain/entity/Notice.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
Labels: ✨ Feature

#211 #139 관리자 > 공지 관리 > 공지 수정
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminNoticeController.java
  src/main/java/com/tikitaka/triptroop/admin/dto/request/AdminNoticeUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminNoticeService.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/notice/domain/entity/Notice.java
  src/main/java/com/tikitaka/triptroop/report/service/ReportService.java
Labels: ✨ Feature

#214 #213 공지 패키지 삭제
  src/main/java/com/tikitaka/triptroop/notice/controller/NoticeController.java
  src/main/java/com/tikitaka/triptroop/notice/domain/type/NoticeType.java
  src/main/java/com/tikitaka/triptroop/notice/dto/response/NoticeDetailResponse.java
  src/main/java/com/tikitaka/triptroop/notice/dto/response/NoticeListResponse.java
  src/main/java/com/tikitaka/triptroop/notice/service/NoticeService.java
Labels: ⚙️Setting

#216 #100 관리자 > 신고 관리 > 신고 목록 조회 완료
  src/main/java/com/tikitaka/triptroop/admin/controller/AdminReportController.java
  src/main/java/com/tikitaka/triptroop/admin/domain/repository/AdminReportRepository.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminReportDetailResponse.java
  src/main/java/com/tikitaka/triptroop/admin/dto/response/AdminReportResponse.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminCategoryService.java
  src/main/java/com/tikitaka/triptroop/admin/service/AdminReportService.java
Labels: ✨ Feature

#218 CI/CD 수정
  .github/workflows/deploy.yml
Labels: ⚙️Setting

#221 #217 README 작성
  README.md
Labels: ⚙️Setting

#220 #219 닉네임 중복 검사 로직 수정
  src/main/java/com/tikitaka/triptroop/user/domain/entity/Profile.java
  src/main/java/com/tikitaka/triptroop/user/service/ProfileService.java
Labels: 🔧Refactor
