Repository 2024-TikiTaka/be-triptroop, pull requests merged in 2024-05, with the labels that each got.

#4 #2 여행 소개 패키지
  src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java
  src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java
  src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java
  src/main/java/com/tikitaka/triptroop/travel/domain/type/TravelType.java
  src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelRequest.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java
  src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
Labels: ⚙️Setting

#3 1# 일정 패키지 작성
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/type/ScheduleType.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ⚙️Setting

#8 #7 채팅 패키지 작성
  src/main/java/com/tikitaka/triptroop/chat/controller/ChatController.java
  src/main/java/com/tikitaka/triptroop/chat/domain/entity/Chat.java
  src/main/java/com/tikitaka/triptroop/chat/domain/repository/ChatRepository.java
  src/main/java/com/tikitaka/triptroop/chat/dto/request/ChatRequest.java
  src/main/java/com/tikitaka/triptroop/chat/dto/response/ChatResponse.java
  src/main/java/com/tikitaka/triptroop/chat/service/ChatService.java
Labels: ⚙️Setting

#10 gitignore 수정
  .gitignore
Labels: ⚙️Setting

#12 #11 Issue, PR 템플릿 수정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️Setting, 📚 Docs

#14 #13 Spring Security 설정
  src/main/java/com/tikitaka/triptroop/_example/controller/ExampleController.java
  src/main/java/com/tikitaka/triptroop/_example/domain/entity/Example.java
  src/main/java/com/tikitaka/triptroop/_example/domain/repository/ExampleRepository.java
  src/main/java/com/tikitaka/triptroop/auth/dto/LoginDto.java
  src/main/java/com/tikitaka/triptroop/common/config/BeanConfig.java
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/security/dto/LoginDto.java
  src/main/java/com/tikitaka/triptroop/security/dto/TokenDto.java
  src/main/java/com/tikitaka/triptroop/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/tikitaka/triptroop/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/tikitaka/triptroop/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/tikitaka/triptroop/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/tikitaka/triptroop/security/handler/LoginFailureHandler.java
  src/main/java/com/tikitaka/triptroop/security/handler/LoginSuccessHandler.java
  src/main/java/com/tikitaka/triptroop/security/service/AuthService.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/Gender.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/MatchStatus.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/SocialProvider.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/UserRole.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/UserStatus.java
  src/main/java/com/tikitaka/triptroop/user/service/UserService.java
Labels: ✨ Feature

#17 DB 변경 및 회원 엔티티 수정
  build.gradle
  src/main/java/com/tikitaka/triptroop/common/config/BeanConfig.java
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/domain/entity/BaseTimeEntity.java
  src/main/java/com/tikitaka/triptroop/common/dto/response/CommonResponse.java
  src/main/java/com/tikitaka/triptroop/common/exception/handler/GeneralExceptionHandler.java
  src/main/java/com/tikitaka/triptroop/user/controller/UserController.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/SocialUser.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/Gender.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/Provider.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/SocialProvider.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/UserRole.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/UserStatus.java
  src/main/resources/ddl.sql
Labels: ✨ Feature, ⚙️Setting

#19 #18 DDL 수정 및 Configuration 추가
  src/main/java/com/tikitaka/triptroop/common/config/BeanConfig.java
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/resources/ddl.sql
Labels: ⚙️Setting

#20 #18 create, insert 문 작성
  src/main/resources/create.sql
  src/main/resources/insert.sql
Labels: ⚙️Setting

#22 #18 SecurityConfig 임시 설정 적용
  .gitignore
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/domain/type/StatusType.java
  src/main/resources/create.sql
Labels: ⚙️Setting

#24 #18 Dockerfile 추가 및 테이블 수정
  Dockerfile
  src/main/resources/create.sql
Labels: ⚙️Setting

#25 #23 일정 계획 등록 추가
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/ScheduleItem.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleItemRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/request/ScheduleItemCreateRequest.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
Labels: ✨ Feature

#26 #5 여행 소개 이미지 등록
  src/main/java/com/tikitaka/triptroop/common/domain/entity/Area.java
  src/main/java/com/tikitaka/triptroop/common/domain/entity/Category.java
  src/main/java/com/tikitaka/triptroop/common/domain/entity/Place.java
  src/main/java/com/tikitaka/triptroop/common/domain/repository/AreaRepository.java
  src/main/java/com/tikitaka/triptroop/common/domain/repository/CategoryRepository.java
  src/main/java/com/tikitaka/triptroop/common/domain/repository/PlaceRepository.java
  src/main/java/com/tikitaka/triptroop/common/domain/type/Visibility.java
  src/main/java/com/tikitaka/triptroop/common/exception/type/ExceptionCode.java
  src/main/java/com/tikitaka/triptroop/image/domain/entity/Image.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/AreaRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
  src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java
  src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java
  src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java
  src/main/java/com/tikitaka/triptroop/travel/domain/type/TravelType.java
  src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelRequest.java
  src/main/java/com/tikitaka/triptroop/travel/dto/response/TravelResponse.java
  src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
  src/main/resources/insert.sql
Labels: ✨ Feature

#49 #41 일정 검색 및 상세 조회
  src/main/java/com/tikitaka/triptroop/companions/domain/entity/Companion.java
  src/main/java/com/tikitaka/triptroop/companions/domain/type/OpenStatus.java
  src/main/java/com/tikitaka/triptroop/image/domain/repository/ImageRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/controller/ScheduleController.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/entity/Schedule.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepository.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryCustom.java
  src/main/java/com/tikitaka/triptroop/schedule/domain/repository/ScheduleRepositoryImpl.java
  src/main/java/com/tikitaka/triptroop/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/tikitaka/triptroop/schedule/service/ScheduleService.java
  src/main/java/com/tikitaka/triptroop/userReview/domain/entity/UserReview.java
Labels: ✨ Feature

#66 #43,#65 여행지 소개 수정, 삭제
  src/main/java/com/tikitaka/triptroop/image/domain/repository/ImageRepository.java
  src/main/java/com/tikitaka/triptroop/image/service/ImageService.java
  src/main/java/com/tikitaka/triptroop/image/util/FileUploadUtils.java
  src/main/java/com/tikitaka/triptroop/travel/controller/TravelController.java
  src/main/java/com/tikitaka/triptroop/travel/domain/entity/Travel.java
  src/main/java/com/tikitaka/triptroop/travel/domain/entity/TravelComment.java
  src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelCommentRepository.java
  src/main/java/com/tikitaka/triptroop/travel/domain/repository/TravelRepository.java
  src/main/java/com/tikitaka/triptroop/travel/dto/request/TravelUpdateRequest.java
  src/main/java/com/tikitaka/triptroop/travel/service/TravelService.java
Labels: ✨ Feature

#64 #31 이메일 계정으로 로그인 구현
  .github/ISSUE_TEMPLATE.md
  src/main/java/com/tikitaka/triptroop/common/config/SecurityConfig.java
  src/main/java/com/tikitaka/triptroop/common/security/dto/LoginDto.java
  src/main/java/com/tikitaka/triptroop/common/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/tikitaka/triptroop/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/tikitaka/triptroop/common/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/tikitaka/triptroop/common/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/tikitaka/triptroop/common/security/handler/LoginFailureHandler.java
  src/main/java/com/tikitaka/triptroop/common/security/handler/LoginSuccessHandler.java
  src/main/java/com/tikitaka/triptroop/common/security/util/TokenUtils.java
  src/main/java/com/tikitaka/triptroop/user/controller/UserController.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/User.java
  src/main/java/com/tikitaka/triptroop/user/domain/entity/UserRefreshToken.java
  src/main/java/com/tikitaka/triptroop/user/domain/repository/UserRepository.java
  src/main/java/com/tikitaka/triptroop/user/domain/type/CustomUser.java
  src/main/java/com/tikitaka/triptroop/user/service/AuthService.java
  src/main/java/com/tikitaka/triptroop/user/service/UserService.java
Labels: ✨ Feature
